version: '3.8'

services:
  designer-forum:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: designer_forum_app
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env.local